"use client";

import { Plus, X } from "lucide-react";
import { LocationSelector } from "./LocationSelector";
import type { SiteLocation } from "@/services/intakeTransfer";

export interface CandidateDraft {
  monthlyRent: string;
  location: SiteLocation | null;
}

interface CandidateSitesSelectorProps {
  candidates: CandidateDraft[];
  onChange: (candidates: CandidateDraft[]) => void;
}

export function CandidateSitesSelector({
  candidates,
  onChange,
}: CandidateSitesSelectorProps) {
  function addCandidate() {
    if (candidates.length >= 3) return;
    onChange([...candidates, { monthlyRent: "", location: null }]);
  }

  function updateCandidate(index: number, update: Partial<CandidateDraft>) {
    onChange(
      candidates.map((candidate, candidateIndex) =>
        candidateIndex === index ? { ...candidate, ...update } : candidate
      )
    );
  }

  return (
    <section className="border border-zinc-800 p-4">
      <div className="flex items-start justify-between gap-4">
        <div>
          <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">
            Candidate Comparison
          </div>
          <p className="mt-1 text-xs text-zinc-500">
            Optional. Add real sites you selected; no locations are generated by the model.
          </p>
        </div>
        <button
          type="button"
          disabled={candidates.length >= 3}
          onClick={addCandidate}
          className="inline-flex items-center gap-1 border border-zinc-700 px-2.5 py-1.5 font-mono text-[10px] uppercase text-zinc-300 disabled:opacity-40"
        >
          <Plus size={12} />
          Add Site
        </button>
      </div>

      <div className="mt-3 space-y-3">
        {candidates.map((candidate, index) => (
          <div key={index} className="space-y-3 border border-zinc-800 bg-zinc-950 p-3">
            <div className="flex items-center justify-between">
              <span className="font-mono text-[10px] uppercase text-zinc-500">
                Option {index + 1}
              </span>
              <button
                type="button"
                aria-label={`Remove candidate ${index + 1}`}
                onClick={() =>
                  onChange(candidates.filter((_, candidateIndex) => candidateIndex !== index))
                }
                className="text-zinc-500 hover:text-zinc-200"
              >
                <X size={13} />
              </button>
            </div>
            <label className="block space-y-2">
              <span className="block font-mono text-[10px] uppercase tracking-[0.14em] text-zinc-500">
                Monthly Rent
              </span>
              <input
                type="number"
                min="1"
                value={candidate.monthlyRent}
                placeholder="5000"
                onChange={(event) =>
                  updateCandidate(index, { monthlyRent: event.target.value })
                }
                className="w-full rounded border border-zinc-800 bg-zinc-900 px-3 py-2 font-mono text-sm text-zinc-100 placeholder:text-zinc-600 focus:border-zinc-600 focus:outline-none"
              />
            </label>
            <LocationSelector
              value={candidate.location}
              onChange={(location) => updateCandidate(index, { location })}
            />
          </div>
        ))}
      </div>
    </section>
  );
}
